name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Sync dependencies (locked if available)
        run: |
          if [ -f uv.lock ]; then uv sync --frozen; else uv sync; fi
      - name: Lint with Ruff
        run: uv run ruff check .
      - name: Type check with ty
        run: uv run ty check .
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml -q
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
